apiVersion: v1 
kind: Service 
metadata:
  labels:
    app: coupon-app 
  name: coupon-app
spec:
  type: NodePort
  ports:
    - port: 9091
      targetPort: 9091
      nodePort: 30288
  selector:
    app: coupon-app