apiVersion: v1
kind: Service
metadata:
  name: docker-mysql
  labels: 
    app: docker-mysql
spec:
  selector:
    app: docker-mysql
  type: NodePort
  ports: 
    - port: 3306 #internally in the cluster - Traffic goes into this port, and gets redirected to the 'targetPort'
      targetPort: 3306 #on the container itself (docker)
      nodePort: 30287 #External port into the cluster