apiVersion: v1 
kind: Service 
metadata:
  labels:
    app: product-app 
  name: product-app
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30289
  selector:
    app: product-app