apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
  - nodePort: 30123 #this is the port that is used by external application to call this service.
    port: 80 #This is the port the nodes use internally to communicate between them selves when calling the web server
    targetPort: 80 #This is the port the container exposes to the members of the cluster.
